 RegisterCommand("help", function()
    msg("Stafuu SV iti ureaza o experienta placuta pe server !")
	msg("---------------------------------------------------")
	msg("General")
	msg("---------------------------------------------------")
	msg("Apasa F2 pentru inventar.")
	msg("Apasa F3 pentru animatii.")
	msg("Apasa F5 pentru telefon")
	msg("Apasa f7 pentru ati vedea facturile")
	msg("Apasa F9 pentru score board")
	msg("Apasa K pentru accesorii")
	msg("Apasa P pentru a deschide mapa.")
	msg("Pentru a acceasa meniurile apasari tasta E")
	msg("--------------------------------------------------")
	msg("Vehicule")
	msg("--------------------------------------------------")
	msg("Apasa U pentru a incuia masina")
	msg("Apasa x pentru ati pune centura")
	msg("Apasa . sau rotita in jos  pentru ati deschide portbagajul ")
	msg("--------------------------------------------------")
	msg("Comenzi")
	msg("--------------------------------------------------")
	msg("/cadou pentru a obtien cadoul zilnic")
	msg("/report pentru a raporta un jucator sau a chema un admin !")
	
    end,false)

function msg(text)
    TriggerEvent("chatMessage","[Server]",{255,0,0},text)
end
